OJ/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('judge.urls')),
    path('admin/', admin.site.urls),
]

judge/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from . import views

app_name='judge'
urlpatterns = [
    path('', views.login_req, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('register/', views.register, name='register'),
    path('problems/', views.problems, name='problems'),
    path('problems/<int:pk>/', views.DetailView.as_view(), name='desc'),
    path('problems/<int:problem_id>/verdict/', views.submission, name='submission'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
]

judge/models.py
from django.db import models
import os
# Create your models here.

class Problem(models.Model):
    title=models.CharField(max_length=100)
    statement=models.TextField()
    difficulty_level=models.CharField(max_length=20)
    code=models.TextField(blank=True)
    def __str__(self):
        return self.title

class Solution(models.Model):
    problem=models.ForeignKey(Problem,on_delete=models.CASCADE)
    verdict=models.CharField(max_length=100)
    def get_upload_path_inp(instance, filename):
        return os.path.join("" ,filename)
    submitted_code=models.FileField(upload_to=get_upload_path_inp)
    time_of_submission=models.DateTimeField('submitted at')
    

class TestCase(models.Model):
    problem=models.ForeignKey(Problem,on_delete=models.CASCADE)
    def get_upload_path_inp(instance, filename):
        return os.path.join("uploads/input/problem_%d" % instance.problem.id,filename)

    def get_upload_path_out(instance, filename):
        return os.path.join("uploads/output/problem_%d" % instance.problem.id,filename)
    
    input=models.FileField(upload_to=get_upload_path_inp)
    output=models.FileField(upload_to=get_upload_path_out)

judge/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

judge/views.py
from math import hypot
from .models import Problem,Solution,TestCase
from django.views import generic
from datetime import datetime
from django.utils import timezone
import os,filecmp
from django.contrib.auth import authenticate, login,logout
from django.shortcuts import render,redirect
from django.urls import reverse
import subprocess
import sys
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.http import HttpResponse, HttpResponseRedirect
from .forms import NewUserForm
from django.contrib import messages



def login_req(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("/problems/")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="judge/login.html", context={"login_form":form})


def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("/problems")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="judge/register.html", context={"register_form":form})
	
def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("/")

def problems(request):
    p=Problem.objects.all()
    context={'p':p}
    return render(request,'judge/problem_list.html',context)

class DetailView(generic.DetailView):
    model = Problem
    template_name = 'judge/problem_desc.html'

def submission(request,problem_id):
	f=request.FILES["solution"] 
	date = str(datetime.now().strftime("%Y_%m_%d_%I_%M_%S_%p"))
	username=request.user.get_username()
	with open("F:/OJ/solution_%d_%s_%s.cpp" % (problem_id,username,date),'wb+') as dest:
		for chunk in f.chunks():
			dest.write(chunk)
   
	subprocess.call("docker run gcc tail -f /dev/null",shell=True)
	output=subprocess.check_output(['docker','ps'],universal_newlines=True)
	x=output.split('\n')
	container_id=""
	for i in x:
		if i.__contains__("gcc"):
			container_id=i[:12]
   
	container_id_with_path=container_id+":/tmp"
	subprocess.call(["docker", "cp", "/root/solution_%d_%s_%s.cpp" % (problem_id,username,date), container_id_with_path])
	subprocess.call(["docker", "cp", "/root/input_%d.txt" % (problem_id), container_id_with_path])
	subprocess.call(['docker','exec', container_id,'g++','/root/solution_%d_%s_%s.cpp'% (problem_id,username,date)])
	subprocess.call(['docker','exec', container_id+'./a.out'> "/root/input_%d.txt" % (problem_id) < "/root/out_%d_%s_%s.txt" % (problem_id,username,date) ])
	
	# subprocess.call(["docker", "cp",  container_id_with_path+"/out_%d_%s_%s.txt" % (problem_id,username,date), "/root/"])
   
	# os.system('g++ F:/OJ/judge/uploads/sol/solution_%d_%s_%s.cpp' % (problem_id,username,date))
	# os.system('a.exe < F:/OJ/judge/uploads/input/problem_%d/single_number_input.txt > F:/OJ/judge/uploads/output/problem_2/out_%d_%s_%s.txt' % (problem_id,problem_id,username,date))

	out1='F:/OJ/out_%d_%s_%s.txt' %(problem_id,problem_id,username,date)
	out2='F:/OJ/judge/uploads/output/problem_%d/single_number_output.txt' %(problem_id)
	if(filecmp.cmp(out1,out2,shallow=False)):
		verdict='Accepted'
	else:
		verdict='Wrong Answer'

	solution=Solution()
	solution.problem=Problem.objects.get(pk=problem_id)
	solution.verdict=verdict
	solution.time_of_submission=timezone.now()
	solution.submitted_code='F:/OJ/judge/uploads/sol/solution_%d_%s_%s.cpp' % (problem_id,username,date)
	solution.save()
	return HttpResponseRedirect(reverse('judge:leaderboard'))	

def leaderboard(request):
	solutions=Solution.objects.all()
	return render(request,'judge/leaderboard.html',{'solutions': solutions})

judge/templates/judge/leaderboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>CodeIt</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body class="override">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'judge:problems' %}">CodeIt</a>
                {% if user.is_authenticated %}
                <span class="navbar-text">
                    Welcome, {{user.username}}</span>
                <span class="navbar-text">
                    <a class="nav-link" href="/logout">Logout</a>
                </span>

                {% else %}
                <span class="navbar-text">
                    <a class="nav-link" href="/">Login</a>
                </span>
                {% endif %}
            </div>
        </div>
    </nav>
    <h2 style="margin-left: 40px;"> Last Submissions:</h2>
    {% if solutions %}
    <ul>
        {% for s in solutions %}
        <p>{{ s.problem.title }} - {{ s.verdict }} - {{ s.time_of_submission }} - <a href={{s.submitted_code}}
                download>Code</a></p>
        {% endfor %}

    </ul>
    {% else %}
    <h3> No data available. </h3>
    {% endif %}
</body>

</html>

judge/templates/judge/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>CodeIt</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body class="override">
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
          aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand">CodeIt</a>
      </div>

    </div>
  </nav>



  {% block content %}

  {% load crispy_forms_tags %}

  <div class="container py-5">
    <h1>Login</h1>
    <form method="POST">
      {% csrf_token %}
      {{ login_form|crispy }}
      <br>
      <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <br>
    <p>Don't have an account? <a href="/register">Create an account</a>.</p>
  </div>
  {% endblock %}


</body>

</html>

judge/templates/judge/problem_desc.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>CodeIt</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body class="override">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'judge:problems' %}">CodeIt</a>
                {% if user.is_authenticated %}
                <span class="navbar-text">
                    Welcome, {{user.username}}</span>
                <span class="navbar-text">
                    <a class="nav-link" href="/logout">Logout</a>
                </span>

                {% else %}
                <span class="navbar-text">
                    <a class="nav-link" href="/">Login</a>
                </span>
                {% endif %}
            </div>

        </div>
    </nav>

    <div class="container">
        <div class="row">
            {% block content %}
            <div class="container">
                <div class="col-md-8 col-md-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>{{problem.title}}</h3>
                        </div>
                        <div class="panel-body">
                            <p>{{problem.statement}}</p>
                        </div>
                        <div class="panel-heading">
                            <h6>{{problem.difficulty_level}}</h6>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="col-md-8 col-md-offset-2">
                    <form action="{% url 'judge:submission' problem.id %}" enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        <div class="panel-body">
                            <h5>Code(In C++ Only):</h5>
                            <input type="file" id="solution" name="solution">
                            <br>
                            <input type="submit" value="Submit" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>


            {% endblock %}
        </div>
    </div>

</body>

</html>

judge/templates/judge/problem_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>CodeIt</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body class="override">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'judge:problems' %}">CodeIt</a>
                {% if user.is_authenticated %}
                <span class="navbar-text">
                    Welcome, {{user.username}}</span>
                <span class="navbar-text">
                    <a class="nav-link" href="/logout">Logout</a>
                </span>

                {% else %}
                <span class="navbar-text">
                    <a class="nav-link" href="/">Login</a>
                </span>

                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            {% block content %}
            {% for ps in p %}
            <ul class="list-group">
                <li class="list-group-item">
                    <a href="{% url 'judge:desc' ps.id %}">{{ ps.title }}</a>
                </li>
            </ul>
            {% endfor %}
            {% endblock %}
        </div>
    </div>

</body>

</html>

judge/templates/judge/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Register</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body class="override">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'judge:login' %}">CodeIt</a>
            </div>
        </div>
    </nav>

    {% block content %}

    {% load crispy_forms_tags %}
    <div class="container py-5">
        <h1>Register</h1>
        <form action="{% url 'judge:register' %}" method="POST">
            {% csrf_token %}
            {{ register_form|crispy }}
            <button class="btn btn-primary" type="submit">Register</button>
        </form>
    </div>

    {% endblock %}
</body>

</html>